run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (*testing.T).Errorf
      - (*testing.T).Fatalf
      - (*testing.T).Logf
      - (*testing.common).Errorf
      - (*testing.common).Fatalf
      - (*testing.common).Logf

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value is not checked"
    - path: _test\.go
      linters:
        - staticcheck
      text: "SA1019"